--- #YAML:1.0
name:               Net-ManageSieve
version:            0.11
abstract:           ManageSieve Protocol Client
author:
    - Steffen Kaiser <cpan@skaus.info>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:        0
    Encode:      0
    IO::Socket:  0
    Socket:      1.3
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
