--- #YAML:1.0
name:                Net-ManageSieve
version:             0.03
abstract:            ManageSieve Protocol Client
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Carp:                          0.01
    Encode:                        0.01
    IO::Socket:                    0.01
    Socket:                        1.3
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Steffen Kaiser <cpan@skaus.info>
